use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};
use uuid::Uuid;

pub fn now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

pub fn new_id() -> String {
    Uuid::new_v4().to_string()
}

pub fn valid_id(id: &str) -> bool {
    Uuid::parse_str(id).is_ok_and(|u| u.to_string() == id)
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Chat {
    pub version: u32,
    pub id: String,
    pub title: String,
    pub created_at: u64,
    pub updated_at: u64,
    pub codex_thread_id: Option<String>,
    pub messages: Vec<Message>,
    pub media: Vec<Media>,
    pub jobs: Vec<Job>,
}

impl Chat {
    pub fn new(title: String) -> Self {
        let timestamp = now();
        Self {
            version: 1,
            id: new_id(),
            title,
            created_at: timestamp,
            updated_at: timestamp,
            codex_thread_id: None,
            messages: vec![],
            media: vec![],
            jobs: vec![],
        }
    }

    pub fn busy(&self) -> bool {
        self.jobs
            .iter()
            .any(|j| matches!(j.status, JobStatus::Queued | JobStatus::Running))
    }
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Message {
    pub id: String,
    pub role: String,
    pub text: String,
    pub media_ids: Vec<String>,
    pub created_at: u64,
    pub job_id: Option<String>,
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Media {
    pub id: String,
    pub name: String,
    /// Internal filename, generated by the server rather than supplied by a browser.
    pub filename: String,
    pub mime: String,
    pub bytes: u64,
    pub kind: String,
    pub created_at: u64,
    pub prompt: Option<String>,
    pub job_id: Option<String>,
}

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    Queued,
    Running,
    Complete,
    Failed,
    Cancelled,
    Interrupted,
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Job {
    pub id: String,
    pub status: JobStatus,
    pub mode: String,
    pub message_id: String,
    pub created_at: u64,
    pub finished_at: Option<u64>,
    pub error: Option<String>,
}

#[derive(Serialize)]
pub struct ChatSummary {
    pub id: String,
    pub title: String,
    pub updated_at: u64,
    pub preview: String,
    pub image_count: usize,
    pub busy: bool,
}

impl From<&Chat> for ChatSummary {
    fn from(chat: &Chat) -> Self {
        Self {
            id: chat.id.clone(),
            title: chat.title.clone(),
            updated_at: chat.updated_at,
            preview: chat
                .messages
                .last()
                .map(|m| m.text.chars().take(100).collect())
                .unwrap_or_default(),
            image_count: chat.media.iter().filter(|m| m.kind == "generated").count(),
            busy: chat.busy(),
        }
    }
}
